version: 2
jobs:
  oreo:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
  mocha:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Double Trouble"
  workflows:
    version: 2
    oreo_mocha:
      jobs:
        - oreo
        - mocha
