version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "installing packages..."
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "testing code..."
      - run: npm install
      - run: npm test
  start_test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "Preparing for test..."
workflows:
  version: 2
  build_test_and_lint:
    jobs:
      - build
      - start_test
      - test:
        # This makes sure that test container will run after the start_test container completed
          requires:
            - start_test
